"use client";

import Image from "next/image";
import "@/styles/globals.css";
import { Inter } from "next/font/google";

import MainNav from "@/components/MainNav";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import { Home } from "lucide-react";
import SideNav from "@/components/SideNav";
import { ScrollArea } from "@/components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className={inter.className + " h-screen overflow-hidden"}>
        {/* top nav */}
        {/* <div className="sticky top-0 left-0 w-full z-50">
          <MainNav />
        </div> */}

        <div className="flex w-full h-screen  bg-gray-100  overflow-hidden">
          {/* <LongList /> */}
          <SideNav />
          <div className=" flex-1 overflow-y-auto ">{children}</div>
          <Toaster />
        </div>
      </body>
    </html>
  );
}

function LongList() {
  return (
    <ul>
      {new Array(100).fill(0).map((v, i) => (
        <li key={i}>{i}</li>
      ))}
    </ul>
  );
}
